- no-pooled:
    model_type: no_pooled
    target: salary
    year: null
    parameters:
    - exp
    - sex
    - elementary_edu
    - highschool_edu
    - postsec_edu
    - undergrad_edu
    - graduate_edu
    - age
    - tenure
    - union
    - part_time
    - public_sector
    - self_emp
    - grad_highschool_refyear
    - grad_college_refyear
    - grad_univ_refyear
    dimensions:
    - industry
    standardize_vars:
    - exp
    - age
    - tenure
    run_settings:
      chains: 4
      tune: 1000
      draws: 1000
      target_accept: 0.98
      batch_size: null
      iterations: null
- no-pooled-reg:
    model_type: no_pooled
    target: salary
    year: null
    parameters:
    - exp
    - sex
    - elementary_edu
    - highschool_edu
    - postsec_edu
    - undergrad_edu
    - graduate_edu
    - age
    - tenure
    - union
    - part_time
    - public_sector
    - self_emp
    - grad_highschool_refyear
    - grad_college_refyear
    - grad_univ_refyear
    dimensions:
    - industry
    standardize_vars:
    - exp
    - age
    - tenure
    run_settings:
      chains: 4
      tune: 1000
      draws: 1000
      target_accept: 0.98
      batch_size: null
      iterations: null
    initial_params:
      prior_dist: laplace
      avg_salary_params: 
        loc: 0
        scale: 0.01
      prior_params:
        loc: 0
        scale: 0.01
      shape_dist: uniform
      shape_params:
        low: 1
        high: 100
      target_dist: gamma
- no-pooled-batch:
    model_type: no_pooled
    target: salary
    year: null
    parameters:
    - exp
    - sex
    - elementary_edu
    - highschool_edu
    - postsec_edu
    - undergrad_edu
    - graduate_edu
    - age
    - tenure
    - union
    - part_time
    - public_sector
    - self_emp
    - grad_highschool_refyear
    - grad_college_refyear
    - grad_univ_refyear
    dimensions:
    - industry
    standardize_vars:
    - exp
    - age
    - tenure
    run_settings:
      chains: 4
      tune: null
      draws: null
      target_accept: 0.98
      batch_size: 400
      iterations: 100
- no-pooled-reg-batch:
    model_type: no_pooled
    target: salary
    year: null
    parameters:
    - exp
    - sex
    - elementary_edu
    - highschool_edu
    - postsec_edu
    - undergrad_edu
    - graduate_edu
    - age
    - tenure
    - union
    - part_time
    - public_sector
    - self_emp
    - grad_highschool_refyear
    - grad_college_refyear
    - grad_univ_refyear
    dimensions:
    - industry
    standardize_vars:
    - exp
    - age
    - tenure
    run_settings:
      chains: 4
      tune: null
      draws: null
      target_accept: 0.98
      batch_size: 400
      iterations: 100
    initial_params:
      prior_dist: laplace
      avg_salary_params: 
        loc: 0
        scale: 0.01
      prior_params:
        loc: 0
        scale: 0.01
      shape_dist: uniform
      shape_params:
        low: 1
        high: 100
      target_dist: gamma