- test:
    model_type: "hierarchical"
    target: "salary"
    year: null
    parameters:
    - exp
    - sex
    - elementary_edu
    - highschool_edu
    - postsec_edu
    - undergrad_edu
    - graduate_edu
    - age
    - tenure
    - union
    - part_time
    - public_sector
    - self_emp
    dimensions:
    - industry
    standardize_vars:
    - exp
    - age
    - tenure
    run_settings:
      chains: 4
      tune: 10
      draws: 10
      target_accept: 0.95
      batch_size: null
      iterations: null
# - test_1:
#     model_type: "hierarchical"
#     target: "salary"
#     year: null
#     parameters:
#     - exp
#     dimensions:
#     - industry
#     standardize_vars:
#     - exp
#     - age
#     - tenure
#     run_settings:
#       iterations: 10
#       chains: 4
#       target_accept: 0.95
#       batch_size: null