- test:
    model_type: "hierarchical_test"
    target: "salary"
    year: null
    parameters:
    - exp
    - sex
    - elementary_edu
    - highschool_edu
    - postsec_edu
    - undergrad_edu
    - graduate_edu
    - age
    - tenure
    - union
    - part_time
    - public_sector
    - self_emp
    - grad_highschool_refyear
    - grad_college_refyear
    - grad_univ_refyear
    dimensions:
    - industry
    standardize_vars:
    - exp
    - age
    - tenure
    run_settings:
      warmup: 2000
      draws: 2000
      chains: 4
      target_accept: 0.95
      batch_size: 400
# - test_1:
#     model_type: "hierarchical"
#     target: "salary"
#     year: 2011
#     parameters:
#     - exp
#     dimensions:
#     - industry
#     standardize_vars:
#     - exp
#     - age
#     - tenure
#     run_settings:
#       warmup: 2000
#       draws: 2000
#       chains: 4
#       target_accept: 0.95
#       batch_size: null