- gamma_gml:
    year: 2009
    standardize_vars:
    - exp
    parameters:
      avg_salary_ind:
        type: intercept
        dist: normal
        initial_values:
          loc: 0
          scale: 1
        dims:
        - industry
        hyperprior: false
        parameterization: centered
      exp:
        type: slope
        dist: normal
        initial_values:
          loc: 0
          scale: 1
        dims:
        - industry
        hyperprior: false
        parameterization: centered
      shape:
        type: shape
        dist: uniform
        initial_values:
          low: 1
          high: 100
        dims: null
        hyperprior: false
        parameterization: centered
