- test:
    model_type: "hierarchical"
    target: "salary"
    year: 2011
    parameters:
    - exp
    dimensions:
    - industry
    standardize_vars:
    - exp
    - age
    - tenure
    run_settings:
      chains: 4
      tune: 200
      draws: 200
      target_accept: 0.95
      batch_size: 100
      iterations: 100
    initial_params:
      mu_dist: "laplace"
      mu_avg_salary_params: 
        loc: 0
        scale: 0.001
      mu_params:
        loc: 0
        scale: 0.001
      sigma_dist: "half_normal"
      sigma_params: 
        scale: 0.001
      shape_dist: "uniform"
      shape_params:
        low: 1
        high: 100
      target_dist: "gamma"
# - test_1:
#     model_type: "hierarchical"
#     target: "salary"
#     year: null
#     parameters:
#     - exp
#     dimensions:
#     - industry
#     standardize_vars:
#     - exp
#     - age
#     - tenure
#     run_settings:
#       iterations: 10
#       chains: 4
#       target_accept: 0.95
#       batch_size: null